name: NPM Publish

on:
  push:
  release: # Run when release is created
    types: [created]

jobs:
  publish-npm:
    # publish only if the event is 'release' (a tag was created) and the tag starts with "v" (aka version tag).
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 14 # use the minimum required version
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
